apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: ProviderNetwork
metadata:
  name: directpnetwork
spec:
  cniType: ovn4nfv
  ipv4Subnets:
  - subnet: 172.16.34.0/24
    name: subnet2
    gateway: 172.16.34.1/24
    excludeIps: 172.16.34.2 172.16.34.5..172.16.34.10
  providerNetType: DIRECT
  direct:
    providerInterfaceName: eth0.101
    directNodeSelector: specific
    nodeLabelList:
    - kubernetes.io/hostname=ubuntu18

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pnw-original-direct-1
  labels:
    app: pnw-original-direct-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pnw-original-direct-1
  template:
    metadata:
      labels:
        app: pnw-original-direct-1
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name": "ovn-networkobj"}]'
        k8s.plugin.opnfv.org/nfn-network: '{ "type": "ovn4nfv", "interface": [{ "name": "directpnetwork", "interface": "net0" }]}'

    spec:
      containers:
      - name: pnw-original-direct-1
        image: "busybox"
        imagePullPolicy: Always
        stdin: true
        tty: true
        securityContext:
          privileged: true
          
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pnw-original-direct-2
  labels:
    app: pnw-original-direct-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pnw-original-direct-2
  template:
    metadata:
      labels:
        app: pnw-original-direct-2
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name": "ovn-networkobj"}]'
        k8s.plugin.opnfv.org/nfn-network: '{ "type": "ovn4nfv", "interface": [{ "name": "directpnetwork", "interface": "net0" }]}'

    spec:
      containers:
      - name: pnw-original-direct-2
        image: "busybox"
        imagePullPolicy: Always
        stdin: true
        tty: true
        securityContext:
          privileged: true
